# Generated by Django 3.0 on 2020-08-31 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_auto_20200831_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('student', models.CharField(max_length=250)),
                ('grade', models.CharField(max_length=40)),
                ('month', models.CharField(max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remaining_due', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAccount',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paid', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=1000)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
    ]
