# Generated by Django 3.0 on 2020-09-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200905_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='prev_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
