# Generated by Django 3.0 on 2020-09-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200905_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=2000)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=2000)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
