# Generated by Django 3.0 on 2020-09-25 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_message_created_date'),
        ('account', '0006_auto_20200923_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='month_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='account',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Grade'),
        ),
    ]
