# Generated by Django 3.0 on 2020-09-25 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
