# Generated by Django 3.0 on 2020-09-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200925_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.AddField(
            model_name='teacheraccount',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.DeleteModel(
            name='Invoices',
        ),
    ]
