# Generated by Django 3.0 on 2020-08-31 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administration.User')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('phone', models.CharField(default=123, max_length=100)),
                ('location', models.CharField(default=23, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyClassTeacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administration.User')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('phone', models.CharField(default=123, max_length=100)),
                ('location', models.CharField(default=23, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='teacher.Grade'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_classteacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default='1990-8-12'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='location',
            field=models.CharField(default=23, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default=123, max_length=100),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_teacher_name', models.CharField(default='Manish', max_length=100)),
                ('math', models.DecimalField(decimal_places=2, max_digits=10)),
                ('English', models.DecimalField(decimal_places=2, max_digits=10)),
                ('social_studies', models.DecimalField(decimal_places=2, max_digits=10)),
                ('science', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nepali', models.DecimalField(decimal_places=2, max_digits=10)),
                ('population', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.Student')),
            ],
        ),
    ]
