# Generated by Django 3.0 on 2020-09-04 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20200904_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='class_teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.MyClassTeacher'),
        ),
    ]
