# Generated by Django 3.0 on 2020-08-31 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20200831_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='student',
            new_name='user',
        ),
    ]
