# Generated by Django 3.0 on 2020-09-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20200904_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleaveapplication',
            name='teacher_username',
            field=models.CharField(max_length=200),
        ),
    ]
