# Generated by Django 3.0 on 2020-08-31 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20200831_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
