# Generated by Django 3.0 on 2020-08-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20200824_0829'),
        ('administration', '0005_remove_student_name'),
    ]

    operations = [
    ]
