# Generated by Django 3.0 on 2020-09-21 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_auto_20200920_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administration.User')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('phone', models.CharField(default=123, max_length=100)),
                ('location', models.CharField(default=23, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
    ]
