# Generated by Django 3.0 on 2020-09-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('query', models.TextField()),
                ('address', models.CharField(max_length=2000)),
                ('phone_no', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
