# Generated by Django 3.0 on 2020-09-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_teacherleaveapplication_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approve', models.BooleanField(default=False)),
            ],
        ),
    ]
