# Generated by Django 3.0 on 2020-09-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_applyforexamination'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(max_length=1000)),
                ('exam', models.BooleanField()),
                ('result', models.BooleanField()),
            ],
        ),
    ]
