# Generated by Django 3.0 on 2020-09-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_publishresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishresult',
            name='exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publishresult',
            name='result',
            field=models.BooleanField(default=False),
        ),
    ]
