# Generated by Django 3.0 on 2020-09-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_auto_20200926_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='user.png', upload_to='images'),
        ),
    ]
