# Generated by Django 3.0 on 2020-09-26 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_auto_20200926_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforexamination',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
